// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// count_kmer_pairs
Rcpp::NumericMatrix count_kmer_pairs(SEXP x, int k, int n, bool zoops);
RcppExport SEXP _monaLisa_count_kmer_pairs(SEXP xSEXP, SEXP kSEXP, SEXP nSEXP, SEXP zoopsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type zoops(zoopsSEXP);
    rcpp_result_gen = Rcpp::wrap(count_kmer_pairs(x, k, n, zoops));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_monaLisa_count_kmer_pairs", (DL_FUNC) &_monaLisa_count_kmer_pairs, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_monaLisa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
